name: caker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_overlay_window: ^0.4.5
  http: ^1.2.2
  html: ^0.15.5

  google_generative_ai: ^0.4.6
  pigeon: ^22.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  installed_apps: ^1.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1  

flutter:
  uses-material-design: true

  assets:
    - assets/NotePad_Icon.jpeg
    - assets/Pact-Logo.jpeg
    - assets/Dictionary-icon.jpeg
